Messages:
  Prefix: '&8[&a&lT&f&lF&8]'
  Header: '&r&a&lT&r&aonic&f&lF&r&foods&r'
  No-Permission: '&fYou do not have permission.'
Settings:
  Sounds:
    Enabled: true
    Pop: "ENTITY_CHICKEN_EGG"
    Bass: "BLOCK_NOTE_BLOCK_BASS"
  Other:
    Metrics: true
    Update-Check: true
# ---- Don't touch below this line ----
Version: 2